### ISSUE TITLE
Make CustomIdentified constructor signature consistent with other constructors

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL3#134]
Currently the constructor signature appears as following:
```
class CustomIdentified(Identified):

    def __init__(self, type_uri: str = None, *, name: str = None,
                 sbol_type_uri: str = SBOL_IDENTIFIED) -> None:
```
Note that all other constructor signatures put the `name` argument first.

**Comment by tcmitchell** [comment]
It is not the case that "all other constructor signatures put the `name` argument first". Here are some classes whose constructors do not put the `name` argument first: Range, Cut, EntireSequence, SubComponent, ComponentReference, ExternallyDefined, LocalSubComponent, SequenceFeature, and VariableComponent. There are more, like Participation and Constraint.

I'm actually not sure why `type_uri` is allowed to be None. I was going to say it is required, but the constructor arguments indicate that it is optional. I suspect code will break if `type_uri` is not specified, but I don't know that for sure.

Let's leave this issue open in order to investigate whether it is ok for the `type_uri` argument to `CustomIdentified` to be unspecified.

**Comment by bbartley** [comment]
It's more an argument about consistency for consistency's sake.  For example,  the constructor for `CustomTopLevel` in the same file puts `name` first:
```
class CustomTopLevel(TopLevel):

    def __init__(self, name: str = None, type_uri: str = None,
                 *, sbol_type_uri: str = SBOL_TOP_LEVEL) -> None:
```
Now, for keyword arguments, to a certain extent, the order doesn't necessarily matter.  Although a user is not obligated to use the keywords and could call a function relying only on the order of the arguments.

Finally, having the `name` parameter first is just what I am used to, which isn't necessarily a strong argument.  However, as a convention in original libSBOL and libSBOLj, the `identity` parameter was always the first parameter.

**Comment by tcmitchell** [comment]
The difference is that `name` (now `identity`, see #135) is a _required_ argument for `CustomTopLevel` (and `TopLevel`) objects. Non-TopLevel objects like `CustomIdentified` the `name` (now `identity`) argument is optional. That is why `name` (now `identity`) comes _after_ the required `type_uri` argument in the `CustomIdentified` constructor.

For constructors that _require_ a `name` (now `identity`), that argument comes first. For constructors where `name` (now `identity`) is optional, it appears in the argument list _after_ all _required_ arguments.

I think this is a change from SBOL2, and the examples you cite are SBOL2 libraries. SBOL3 Best Practices (Section 7.2 of the [SBOL 3.0 specification](https://sbolstandard.org/docs/SBOL3.0specification.pdf)) explains how identities of compliant non-TopLevel objects are to be constructed.
