### ISSUE TITLE
Using TopLevel objects without having their definitions

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/pySBOL3#136]
Do we have a way to use a TopLevel object without actually having its definition in the namespace?

For example, in Intent Parser, we often work with collections of strains (i.e., Components).  Those strains are often very big, and downloading them all from SynBioHub would be painful and not really necessary: we aren't reasoning about them, we're just pointing to them.

Since they are TopLevel objects, we are not required to include them in the document, but I believe that pySBOL3 will force us to include them in the document in order to reference them.  

Can we have some way to let one work with an "out of document" pointer to an object that has appropriate type information for purposes of reasoning but otherwise is not a fully instantiated object?

**Comment by bbartley** [comment]
One option is to do a non-recursive fetch from SBH (for example, to avoid pulling down massive amounts of data associated with a strain).  Another option is to create a local stub.

**Comment by jakebeal** [comment]
Concrete example: making a Component for a sample that has two SubComponents:
- media = M9-media
- strain = E. coli DH5-alpha 

Where M9-media and E. coli DH5-alpha are referenced just by URI, and not in the document.

**Comment by tcmitchell** [comment]
Using SubComponents won't work for this. My read of the SBOL spec is that the SubComponent MUST be defined in the document. In the language of pySBOL3, the SubComponent is an OwnedObject, and thus is a Python object in memory, rather than a reference by URI.

What about using an `ExternallyDefined`? This seems to be exactly the purpose of the ExternallyDefined class. From Section 6.5.1.4:

> The ExternallyDefined class has been introduced so that external definitions in databases like ChEBI or UniProt 22
can be referenced.

Here's how that might look, if I understand your example:

```python
>>> import sbol3
RDFLib Version: 5.0.0
>>> c = sbol3.Component('foo', sbol3.SBO_DNA)
>>> ed1 = sbol3.ExternallyDefined([sbol3.SBO_DNA], 'https://synbiohub.example.org/m9-media')
>>> ed2 = sbol3.ExternallyDefined([sbol3.SBO_DNA], 'https://synbiohub.example.org/e-coli-DH5-alpha')
>>> c.features = [ed1, ed2]
>>> c.features
[<sbol3.extdef.ExternallyDefined object at 0x7fc6802e5400>, <sbol3.extdef.ExternallyDefined object at 0x7fc6802e5790>]
```

Does this cover what you're trying to accomplish? Or does it miss the mark?

**Comment by jakebeal** [comment]
I'm afraid that I was unclear: I meant that the SubComponents are in the document, but their "instanceOf" links point to Component definitions that are not in the document.

**Comment by jakebeal** [comment]
The minimal example might just be this:

```python
>>> import sbol3
RDFLib Version: 5.0.0
>>> c = sbol3.Component('foo', sbol3.SBO_DNA)
>>> sc1 = sbol3.SubComponent('https://synbiohub.example.org/m9-media')
>>> sc1 = sbol3.SubComponent('https://synbiohub.example.org/e-coli-DH5-alpha')
>>> c.features = [sc1, sc2]
>>> c.features
```

**Comment by tcmitchell** [comment]
That looks good to me. I don't see any language in the SBOL 3.0 spec that says a SubComponent must refer to a Component (via instanceOf) contained in the same document.

I think we should add this example to the unit tests, including a round trip of the resulting file. That way we can ensure that this continues to work, or be alerted if future validation rules cause this to break. I can add comments to the unit test that point to this issue and explain that this is an Intent Parser use case.

Thoughts?

**Comment by jakebeal** [comment]
That's right; the spec supports this, and we just have to make sure that the library continues to do so.

@tramyn Please take note --- intent parser should be able to use either no pull or shallow pulls from SynBioHub.

**Comment by tramyn** [comment]
@jakebeal If I use the code above to encode a list of strains, will variable `c` replace the use of an SBOL collection for grouping a list of strains assigned to a measurement?

```python
c = sbol3.Component('foo', sbol3.SBO_DNA) 
```

**Comment by jakebeal** [comment]
No you'd still use your collection. But rather than adding a list of `Component` objects to the collection, you'd just add a list of URIs to the collection.

**Comment by tramyn** [comment]
So would it look something like this?

```python3
strains = ['https://synbiohub.example.org/B_subtilis_IPTG_JAB546',
           'https://synbiohub.example.org/B_subtilis_IPTG_JAB547', 
           'https://synbiohub.example.org/B_subtilis_IPTG_PY79']
strain_collection = Collection('strain_collection1')
strain_collection.members = strains
```

**Comment by jakebeal** [comment]
Yes, modulo my ability to read code correctly.

**Comment by tcmitchell** [comment]
I don't think that will work. I think the items in the `strains` list need to be instances of some SBOL3 class. And a class that is a `TopLevel` (like `Component`), not one that is simply `Identified` (like `SubComponent` or `ExternallyDefined`).

I don't know what kind of thing your strains want to be, perhaps Jake can tell us.

**Comment by jakebeal** [comment]
The strains are all Component objects

**Comment by tcmitchell** [comment]
@tramyn your example above should work. The `members` property is a `ReferencedObject` and will accept either strings or instances of a `TopLevel` class.

It is not clear to me whether it is valid to reference objects outside of the current SBOL Document. That's something that will come up when validation is implemented. @jakebeal can a `Collection` have members that are outside the document, or is it required that all members of the `Collection` must appear within the document?

**Comment by jakebeal** [comment]
Since all members of a `Collection` must be `TopLevel` objects, they can be outside of the document.

**Comment by tcmitchell** [comment]
I have encoded a unit test for the  @jakebeal [example](https://github.com/SynBioDex/pySBOL3/issues/136#issuecomment-760486898) above. See #141 

Are there other desired actions on this issue? Or is this settled and can be closed?

**Comment by jakebeal** [comment]
If @tramyn has what she needs, then I'm fine with closing.

**Comment by tramyn** [comment]
@tcmitchell could you point me to the unit test for this? I would like to look before closing this issue.

**Comment by tramyn** [comment]
@tcmitchell I am looking at test_external_instance_of() that was written for this issue.
It looks like I am required to create a `sbol3.Component()` for listing my strains and each strain I want to reference from SBH must be represented as a `sbol3.SubComponent()`.
Two questions with this test case:

- On this [line](https://github.com/SynBioDex/pySBOL3/blob/a4c700230937d86dcbfc79fac0ebbabbdbf94fe6/test/test_subcomponent.py#L33], I am unclear why doc2 is copying the contents of doc1. What is this purpose for writing contents from one document to another document in this test case?
- To connect this test case with the the use of `sbol3.Collection`, will I need to modify my above code to look like this?
```python3
m9_media = 'https://synbiohub.example.org/m9-media'
sc1 = sbol3.SubComponent(m9_media)

e_coli = 'https://synbiohub.example.org/e-coli-DH5-alpha'
sc2 = sbol3.SubComponent(e_coli)

c_uri = 'https://synbiohub.example.org/component1'
c = sbol3.Component(c_uri, sbol3.SBO_DNA)
c.features = [sc1, sc2]

strains = [sc1.identity, sc2.identity]
strain_collection = Collection('strain_collection1')
strain_collection.members = strains

doc1 = sbol3.Document()
doc1.add(c)
doc1.add(strain_collection)
```

**Comment by tcmitchell** [comment]
@tramyn I said [here](https://github.com/SynBioDex/pySBOL3/issues/136#issuecomment-762876615) that [your example](https://github.com/SynBioDex/pySBOL3/issues/136#issuecomment-762496103) should work. I was referring to the example from [this comment](https://github.com/SynBioDex/pySBOL3/issues/136#issuecomment-762496103). This example is encoded in a unit test that was incorporated in PR #140. You can also see that unit test [here](https://github.com/SynBioDex/pySBOL3/blob/a4c700230937d86dcbfc79fac0ebbabbdbf94fe6/test/test_collection.py#L24).

The unit test you are referring to implements the [example](https://github.com/SynBioDex/pySBOL3/issues/136#issuecomment-760486898) @jakebeal wrote earlier in this issue. I said [here](https://github.com/SynBioDex/pySBOL3/issues/136#issuecomment-760494192) that we should encode that example in a unit test, and in [this comment](https://github.com/SynBioDex/pySBOL3/issues/136#issuecomment-763148452) I was letting @jakebeal know that I had done so.

It seems that the wires crossed and you interpreted the @jakebeal example as the unit test related to your [example](https://github.com/SynBioDex/pySBOL3/issues/136#issuecomment-762496103).

Does that clear things up?

On to the unit test questions:
1. The unit test does a round trip of the data to ensure that the data remains properly encoded after being written and read. I chose to use the `read_string(write_string)` instead of the more laborious creating temp directory, writing file, reading file approach. They amount to the same thing.
2. As I've established above, this unit test is unrelated to your example code.

**Comment by tramyn** [comment]
@tcmitchell Okay. I have found my answer. I have no concerns at this point if you would like to move forward and close this issue.

**Comment by tcmitchell** [comment]
@jakebeal @tramyn I'm closing this issue. Feel free to reopen it if we've missed anything.
