### ISSUE TITLE
ValueError when creating a Feature object

### ISSUE THREAD

**Issue by tramyn** [SynBioDex/pySBOL3#149]
This is a follow up message from slack. I am getting a ValueError from sbol3 when creating a Feature object indicating that `displayId` is empty. However, the specification says that displayId is optional. Please, can someone take a look at this and see what needs to be done here? 

```python3
Traceback (most recent call last):
  File "my_workspacev/lib/python3.7/site-packages/sbol3/feature.py", line 11, in __init__
    super().__init__(identity, type_uri)
  File "my_workspace/lib/python3.7/site-packages/sbol3/identified.py", line 27, in __init__
    self._display_id = self._extract_display_id(self.identity)
  File "my_workspace/lib/python3.7/site-packages/sbol3/identified.py", line 61, in _extract_display_id
    raise ValueError(msg)
ValueError: "" is not a valid displayId. A displayId MUST be composed of only alphanumeric or underscore characters and MUST NOT begin with a digit.
```

**Comment by tramyn** [comment]
Code to reproduce this error:
```python3 
media_template = Feature(identity='https://sd2e.org/media_template',
                         type_uri=sbol_constants.SBO_FUNCTIONAL_ENTITY)
```

**Comment by bbartley** [comment]
I believe `Feature` is an abstract base class, so you probably shouldn't be calling the constructor for it.  @tcmitchell can confirm.

It looks to me like maybe you might want to instantiate a `Component` for the example above, if this is intended to be a template for a `CombinatorialDerivation`

**Comment by tramyn** [comment]
It seems like I got the above ValueError because I was providing an invalid value for the identity field. I had to remove the `#` to resolve the error. Is there a way for the library to report this error when validation is performed?

**Comment by tcmitchell** [comment]
There's a lot to unpack here.

1. To the best of my knowledge, `Feature` is an abstract class that is not supposed to be instantiated directly. @jakebeal agrees with this assessment. This is _not_ noted in the specification, which appears to be a bug in the specification. pySBOL3 marks the class as abstract but that doesn't appear to be accompanied by any automatic enforcement.
2. `displayId` is optional, however by supplying `identity` you are implicitly supplying a `displayId`. The displayId is defined to be the last element in the path of a URL. (See Section 5.1 of the specification). In your example you use `identity='https://sd2e.org/#media_template'`, so the displayId extracted from that URL is `#media_template`, which is the last element of the URL's path.
3. The error message you are getting indicates what the problem is: "A displayId MUST be composed of only alphanumeric or underscore characters and MUST NOT begin with a digit.". Unfortunately the `#` is confusing the parsing of the URL, so the displayId in the error message is empty. `#media_template` is not a valid displayId because of the `#` character. 
4. In your example you set the type_uri (`type_uri=sbol_constants.SBO_FUNCTIONAL_ENTITY`). That almost certainly does not do what you want it to do. `type_uri` indicates the class of the entity, and is distinct from a property of the entity. I would expect `sbol3.SBO_FUNCTIONAL_ENTITY` to be used as a `type` property of a component, not as a `type_uri`.
5. I'm a little worried about your imports. You are using an unqualified `Feature` class, which makes me think that you are using wildcard imports. I hope I'm wrong about that. If I'm not wrong, please see my email rant about wildcard imports. I can resend if you can't find it. And perhaps you are defining your own constants in an `sbol_constants` module, but `sbol3` defines that and other constants.
6. You ask if there is a way for the library to report this error when validation is performed. Are you saying that you'd like to have the error delayed until validation is performed? That would mean allowing bad values in objects until validation is invoked. Is that what you are requesting here?

I also wonder if @jakebeal can provide some advice about how to accomplish what you're really trying to do here. My reply here is fairly low level. Jake can provide a higher level view that would probably have avoided the whole issue in the first place. I suspect you either wanted to create a `Component` or one of the subclasses of `Feature`. But I don't know enough to be able to provide that level of guidance.

**Comment by jakebeal** [comment]
I believe that you want to use `LocalSubComponent` as the type of Feature.

**Comment by tcmitchell** [comment]
Using `LocalSubComponent` the example above would be:

```python
>>> lsc = sbol3.LocalSubComponent(types=[sbol3.SBO_FUNCTIONAL_ENTITY])
>>> lsc.types
['https://identifiers.org/SBO:0000241']
```

Note that the `types` argument is a list (or more generally an iterable). 

If you want to set an identity and displayId, it would be:

```python
>>> lsc = sbol3.LocalSubComponent(types=[sbol3.SBO_FUNCTIONAL_ENTITY], identity='https://sd2e.org/media_template')
>>> lsc.types
['https://identifiers.org/SBO:0000241']
>>> lsc.identity
'https://sd2e.org/media_template'
>>> lsc.display_id
'media_template'
```

Note: the identity and display_id **_will be overwritten_** when this `LocalSubComponent` is added to a TopLevel, and will be assigned a compliant identity and display_id based on their parent. So there's really no point passing the `identity` argument. See Section 7.2 of the spec. As such this entity will be assigned a display_id along the lines of `LocalSubComponent2`.

**Comment by tramyn** [comment]
I guess I should have mentioned that I tried creating `LocalSubComponents` and reference them to a `Component.features`. 
It looks something like this:
```python3 
media_template = LocalSubComponent(identity='https://sd2e.org/media_template',
                                   types=[sbol_constants.SBO_FUNCTIONAL_ENTITY])
media_template.name = 'media template'

media_variants = []
for media in self._medias:
      media_variants.append(media.to_sbol())

media_variable = VariableFeature(cardinality=sbol_constants.SBOL_ONE)
media_variable.variable = media_template

all_sample_templates = [media_template]
sample_template = Component(identity='https://sd2e.org/measurement_template', 
                            component_type=sbol_constants.SBO_FUNCTIONAL_ENTITY)
sample_template.name = 'measurement template'
sample_template.features = all_sample_templates
```
However, this is causing a TypeError when Intent Parser tries to execute this code 
```python3 
sample_template.features = all_sample_templates
```

This is the TypeError that I got.
```python3 
  File "my_workspace/lib/python3.7/site-packages/sbol3/object.py", line 25, in __setattr__
    self.__dict__[name].set(value)
  File "my_workspace/lib/python3.7/site-packages/sbol3/property_base.py", line 137, in set
    items = [self.from_user(v) for v in value]
  File "my_workspace/lib/python3.7/site-packages/sbol3/property_base.py", line 137, in <listcomp>
    items = [self.from_user(v) for v in value]
  File "my_workspace/lib/python3.7/site-packages/sbol3/ownedobject.py", line 21, in from_user
    raise TypeError(f'Expecting SBOLObject, got {type(value)}')
TypeError: Expecting SBOLObject, got <class 'list'>
```

I noticed TypeError indicates that I should assign an SBOLObject and not a list so I then modified my code to look like this:
```python3 
sample_template.features = media_template
```

Doing so gave me this error:
```python3
  File "ip_env/measurement_intent.py", line 153, in to_sbol
    sample_template.features = media_templates[-1]
  File "my_workspace/lib/python3.7/site-packages/sbol3/object.py", line 25, in __setattr__
    self.__dict__[name].set(value)
  File "my_workspace/lib/python3.7/site-packages/sbol3/property_base.py", line 137, in set
    items = [self.from_user(v) for v in value]
TypeError: 'LocalSubComponent' object is not iterable
```

I then switched over to creating `sbol3.Features` object to see if I can assign sample_template.features using `sbol3.Features() `but got the reported error above. If I shouldn't use `sbol3.Features` then how can I successfully assign a `sbol3.Components.features` with a list of `LocalSubComponents`? 

Lastly, as a side note, I don't like using wild card imports so this shouldn't be an issue. I notice that pysbol3 uses wild card references so when I look at pysbol's code, it makes it difficult for me to know what form of imports the library is using, whether its referring to sbol3 constants that I am not aware of.

**Comment by tcmitchell** [comment]
Hmm. Those look like possible sbol3 issues. I'll dig into that a bit and see what I find out.

As far as the imports go, you should just do `import sbol3` and then reference everything via the sbol3 module, like `sbol3.LocalSubComponent` and `sbol3.SBO_FUNCTIONAL_ENTITY`. When browsing the module for how to invoke the code, look at the unit tests, which should all do it this way. The files that make up the actual module, in the sbol3 directory, have to do things differently because the module is in the process of being defined as these files are loaded, so they can't import `sbol3` because that would be circular and fail.

**Comment by tcmitchell** [comment]
This is odd. I'm using the current HEAD of pySBOL3 and your test case above works fine when `features` is set to a list.

```python
    def test_features(self):
        media_template = sbol3.LocalSubComponent(identity='https://sd2e.org/media_template',
                                                 types=[sbol3.SBO_FUNCTIONAL_ENTITY])
        media_template.name = 'media template'

        # media_variants = []
        # for media in self._medias:
        #     media_variants.append(media.to_sbol())

        media_variable = sbol3.VariableFeature(cardinality=sbol3.SBOL_ONE)
        media_variable.variable = media_template

        all_sample_templates = [media_template]
        sample_template = sbol3.Component(identity='https://sd2e.org/measurement_template',
                                          component_type=sbol3.SBO_FUNCTIONAL_ENTITY)
        sample_template.name = 'measurement template'
        sample_template.features = all_sample_templates
        self.assertEqual(1, len(sample_template.features))
        self.assertEqual(media_template.identity,
                         sample_template.features[0].identity)
```

I probably don't have the full context that you have in your environment, so maybe something more is at play.

Can you please double check the version of sbol3 that you are using:

```python
>>> sbol3.__version__
'1.0a6'
```

Yours should probably say '1.0a5' (mine is the development version, so is at 1.0a6 which has not been released yet.

**Comment by tramyn** [comment]
This issue has been resolved. This was an Intent Parser error that was caused by improper usage in appending vs. extending a list of `sbol3.LocalSubComponent` objects.

**Comment by tcmitchell** [comment]
I'm glad you were able to find the problem!
