### ISSUE TITLE
str function for ValidationReport

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/pySBOL3#232]
Right now, in order to print the contents of a validation report, I need to iterate over it twice:
````
for e in doc.validate().errors: print(e);
for w in doc.validate().warnings: print(w);
````

It would be nice if there were a `_str_` function on the report, just like there is on its errors and warnings, so I could just say `print(doc.validate())`

**Comment by tcmitchell** [comment]
Do you want `ValidationReport.__str__` to simply join the ValidationError and ValidationWarning strings with newlines? Or do you want more formatting than that?

Another option might be to give `ValidationReport` an iterator method (`__iter__`?) so that it is possible to iterate over all of the errors and warnings in one go, printing them out like so:

```python
report = doc.validate()
for item in report:
    print(item)
```

Note to implementer: `ValidationWarning` does not yet have a `__str__` method.

**Comment by jakebeal** [comment]
Simple is fine; I'm just looking for a __str__ function that acts as a macro wrapping the iteration.
