### ISSUE TITLE
Design: copy / clone / rename

### ISSUE THREAD

**Issue by tcmitchell** [SynBioDex/pySBOL3#235]
The notion of copying an object or a set of objects, comes up often in SBOL applications. There are a number of ways in which users want to copy objects. Those include, and are not limited to:

* Moving a `TopLevel` and all its dependent objects from one document to another
* Moving a `TopLevel` to a different `Namespace` while maintaining referential integrity within the `TopLevel` and its dependent objects
* Copying an object hierarchy in order to manipulate the copy in some way
  * Is this confined to copying a TopLevel?
* Moving an entire `Document` into a different namespace while maintaining referential integrity

We should consider the various ways applications might want to manipulate objects on the copy/clone/rename spectrum and design a set of APIs to support those operations. These APIs will need to be documented so that users can understand the differences and choose the correct API for their use case.

This issue will serve as a place to design the APIs and their implementations. Please edit the list of use cases above as needed, and please add comments to the issue as you see fit.

**Comment by jakebeal** [comment]
Bullet 1 is good by me. I think it could be implemented on either or both of `Document` and `TopLevel` 

I'd like to propose that bullet 2 and bullet 4 be consolidated into the following operation:

* Moving a set of `TopLevel` objects to a different namespace while maintaining referential integrity within and between all `TopLevel` objects in the set and also their dependent objects.

In this case, moving an individual TopLevel is a set containing one and moving a whole document is a set containing all. I'd suggest a method like `Document.change_object_namespace`.

For bullet 3, I'd also like to change that from an individual to a set:

* Copy a collection of `TopLevel` objects in order to make a collection of derivative objects to manipulate. Each `TopLevel` maps to a new identity, and referential integrity is retained within and between all `TopLevel` objects in the set and also their dependent objects.

I think this also needs to be a function on `Document`, e.g., `Document.clone`

**Comment by tcmitchell** [comment]
Reorganizing @jakebeal's comment a bit, it sounds like we're proposing 3 methods, give or take.

1. `TopLevel.change_document(new_doc: Document)` - Removes the object and all its dependents from their current document, then adds the object  and all its dependents to document `new_doc`. No change to namespace.
    * We could have a second method `Document.change_document(new_doc: Document)` that moves all top level objects from their current document to a new document by repeatedly calling `TopLevel.change_document`. I'm not sure this is the way to go though. It feels like we would want a `Document.add_all(other_doc: Document)` method that moves all objects from `other_doc` into the target Document.
2. `Document.change_object_namespace(top_levels: Iterable[TopLevel], new_namespace: str)` - changes the namespace of all top level objects in `top_levels` to `new_namespace`, regardless of the previous value, while maintaining referential integrity among all the top level objects in `top_levels`, including their dependents.
    * Do we want to use a map for the new namespaces so that an old namespace is mapped to a new namespace, providing more flexibility at the cost of complicating things? If so, what do we do if an objects namespace is not included in the map?
3. `Document.clone(top_levels: Iterable[TopLevel]) -> List[TopLevel]` - copies all TopLevel objects in top_levels, returning a list of newly created objects that are identical to the original collection except that they are not in any Document. Referential integrity is automatically maintained since the contents of the objects do not change (except for the document attribute).
    * The description above says "Each TopLevel maps to a new identity" and I don't know what that means in this context. Do you want `Document.clone` to take an additional `namespace` argument and also run `change_object_namespace` on the clones?

This was originally `copy` and `clone` and it seems now to be more `clone`, `change_namespace`, and `change_document`. Does that sound like the right set of functionality?

**Comment by bbartley** [comment]
1. Sounds ok.  Minor quibble, I would prefer `TopLevel.move`, but basically agree with the contract as described.  
2.  Does this perform an in-place change in namespace of all the objects in the `Document`?  Or does it return a copy of the original `Document` with the new namespace.  Also, is a map necessary?  I think it can be done without the map, by using some smart heuristic to infer which references need to be mapped into the new namespace.  A possible heuristic is to look for all `ReferencedObject` properties, and check whether a `lookup` operation succeeds, which thus indicates that the reference needs to be mapped into the new namespace.
3. I would like the method to apply to a `TopLevel` object.  `TopLevel.clone` would create an identical `TopLevel` not in the `Document`.

**Comment by jakebeal** [comment]
This formulation works for me.

In answer to the questions:
- I believe that the objects in `top_levels` do need to be members of the target `Document`. If they aren't, then the document may not be able to access them to copy them.
- I don't have a strong opinion about whether the copies should be added to the document. My default would be to start by _not_ adding, since adding is easy if needed.

**Comment by bbartley** [comment]
Not expressing an opinion here, but I would like to know how to use this for a use case that I have encountered while developing the COMBINE tutorials, which I think will turn out to be a fairly common use case.  The use case basically involves merging `Documents`.  For example, I want to integrate objects taken from multiple separate files representing libraries of parts into a new `Document`.  Based on Tom's description above, I think I can see a couple of different ways to accomplish this, but I am curious which method(s) would be the most straightforward and easy for a beginner to understand?

**Comment by tcmitchell** [comment]
@jakebeal 
> * I believe that the objects in `top_levels` do need to be members of the target `Document`. If they aren't, then the document may not be able to access them to copy them.

If objects are provided in `top_levels`, how would the document _not_ be able to access them?

Your reply makes me wonder if you are intending to provide a list of URIs (i.e. identities) as `top_levels`. The intent of this call is that the `top_levels` argument is a set of _objects_, not a set of _object references_. Are we on the same page?

**Comment by tcmitchell** [comment]
@bbartley 
> Not expressing an opinion here, but I would like to know how to use this for a use case that I have encountered while developing the COMBINE tutorials, which I think will turn out to be a fairly common use case. The use case basically involves merging `Documents`. For example, I want to integrate objects taken from multiple separate files representing libraries of parts into a new `Document`. Based on Tom's description above, I think I can see a couple of different ways to accomplish this, but I am curious which method(s) would be the most straightforward and easy for a beginner to understand?

Thank you for asking this question. This is use case is what I was hinting at in the sub-bullet under `TopLevel.move`. I have provided two options there and we need to either include them both, or choose one (or none).

The first option is `Document.move(new_doc: Document)`, which would be used as follows:

```python
# This is the target document into which we will accumulate objects from other documents
doc = sbol3.Document()

# Load another document
tmp_doc = sbol3.Document()
tmp_doc.read('some_sbol.ttl')

# Push all objects in `tmp_doc` into `doc`
tmp_doc.move(doc)
```

The second option, and the one I think I prefer, is a pull instead of a push. The catch is that the programmer needs to understand that objects can only reside in one document at a time, and thus the `add_all` method _moves_ the objects. So `tmp_doc` will be empty after the `add_all` method completes.

```python
# This is the target document into which we will accumulate objects from other documents
doc = sbol3.Document()

# Load another document
tmp_doc = sbol3.Document()
tmp_doc.read('some_sbol.ttl')

# Pull all objects in `tmp_doc` into `doc`
doc.add_all(tmp_doc)
```

**Comment by bbartley** [comment]
Thanks, @tcmitchell .  I like that the merge operation is simple which is what I want for a tutorial!  A couple of observations.

WRT the push operation:
```python
tmp_doc.move(doc)
```
This will probably work for most `Document` merge operations given the premise of my original question.  But there may still be cases where the user doesn't want to remove objects from the original `Document`.  It would be nice to simply copy them over to the new `Document` without deleting them.
```python
tmp_doc.copy(doc)
```
Now, I realize that the same operation could be performed in two steps using the `clone` method and `doc.add`.  But what I like about the above is that the semantics of `move` and `copy` are similar to the Unix file operations, which is easy for a beginner to understand in the context of a tutorial.

So for method 4) above, I would propose something like this:
```python
Document.copy(doc: Document, top_levels: Iterable[TopLevel]=None, new_names=None: Dict[str, Union[str,tuple]]=None) -> List[TopLevel]
```
This would allow `copy` to be invoked very simply for the above use case, but would also optionally allow for the more complicated mappings into new URIs.  If this suggestion just soundsoverly-complicated, then feel free to disregard.  I don't want to hold things up.

WRT the pull operation:
```
doc.add_all(tmp_doc)
```
Can we use a more descriptive method name such as `pull` or `import`?  The reason I say this is because the directionality of the operation is ambiguous given the current method name.  In fact, if I were to encounter this statement without any prior knowledge, I would assume that the method is going to add all the objects from `doc` to `tmp_doc`, which is exactly the opposite of the behavior described.

**Comment by tcmitchell** [comment]
What if my code example had said:
```python
doc.add_all(tmp_doc.objects)
```
Is that still ambiguous to you?

I'm considering making `Document` an iterable of `TopLevel` so that a user could iterate over the objects in a `Document` like this:
```python
for tl in doc:
    print(tl.identity)
```
From there it's a pretty small leap to go from `doc.add_all(tmp_doc.objects)` to `doc.add_all(tmp_doc)` since in this context `tmp_doc` is an `Iterable[TopLevel]`. Additionally we don't need your extra `Document` argument to `Document.copy` since passing the document fulfills the `top_levels` argument.

**Comment by bbartley** [comment]
```
doc.add_all(tmp_doc.objects)
```
In this case, the directionality of the operation is immediately obvious to me.  Although, I then begin to wonder why the method is called `add_all`.  Why not just `doc.add(tmp_doc.objects)`?

I definitely like the idea of making the `Document` iterable and how that would work with `copy`!

**Comment by tcmitchell** [comment]
Ok, great. Let's modify `doc.add()` to take a `TopLevel` or an `Iterable[TopLevel]` AND make `Document` iterable. Then
```python
doc.add(tmp_doc.objects)
```
is equivalent to
```python
doc.add(tmp_doc)
```
So for your use case about merging documents, it would just be `doc.add(other_doc)`. How does that sound?

**Comment by bbartley** [comment]
I like that. It's very concise and I think I would be able to easily intuit what is happening if I encountered it without any prior knowledge.  Good tutorial stuff!

**Comment by jakebeal** [comment]
One small note about naming and consistency: when we use `doc.add(X)` currently, it adds a thing that is currently in _no_ document, and (iirc) throws an error if X is already added to something else.  The word "add" also suggests to me that it's only a positive operation, not one that also removes.

Thus, I think if would be good to have the "pull an object from its current document to this document" operation have a different name that also suggests removal from its old context, such as `doc.migrate(X)` or `doc.import(X)`. I don't have a strong opinion on what the name should be, just that we should clearly distinguish "add something that had no previous home (and exception if it had one)" from "move something from its previous home (and exception if it didn't have one)".

**Comment by tcmitchell** [comment]
### Progress report

* Added `Document.remove()` (#365) - this change adds methods to support the removal of objects from documents.
* Added `Document.__iter__()` (#366) - this change makes Documents iterable
* Added `Document.migrate()` (#366) - this change _moves_ objects into the target Document from whatever document they may have been in

**Comment by tcmitchell** [comment]
@bbartley your document merge use case would now use the new `Document.migrate`:

```python
# This is the target document into which we will accumulate objects from other documents
doc = sbol3.Document()

# Load another document
tmp_doc = sbol3.Document()
tmp_doc.read('some_sbol.ttl')

# Migrate all objects in `tmp_doc` into `doc`
doc.migrate(tmp_doc)
```

From our discussion above, this is a _pull_ operation. Objects are pulled into the target document, in this case `doc`. I think this also addresses comments from @jakebeal in https://github.com/SynBioDex/pySBOL3/issues/235#issuecomment-853805595

**Comment by tcmitchell** [comment]
### Progress report

* Added `Document.change_object_namespace` (#367)

**Comment by tcmitchell** [comment]
I'm calling this done with the 1.0b12 release. Further work should be done under specific issues for bug fixes or new features.
