### ISSUE TITLE
Accelerate lookup()

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/pySBOL3#237]
The `lookup()` method uses `document.find()`, and in turn `document.find()` searches the entire document in a linear fashion. This is causing significant slowdowns for me once the documents become large in size and I'm doing significant graph operations on them (e.g., pointer-chasing through a document to process items in the order of dependencies).

I think it should be possible to have a "fast-track" lookup via hash tables for when we know we have a full URI.

**Comment by bbartley** [comment]
I think one way to implement this that wouldn't require extensive refactoring is for the `ReferencedObjectMixin` interface to capture a tuple of both the URI reference and object.  For example:

Something like this (not tested):
```
    @staticmethod
    def from_user(value: Any) -> Tuple[rdflib.URIRef, SBOLObject]:
        if isinstance(value, SBOLObject):
            value = (rdflib.URIRef(value).identity, value)
        elif isinstance(value, str):
            value = (rdflib.URIRef(value.identity), None)
        else:
            raise TypeError(f'Expecting string, got {type(value)}')
        return value
```

The `lookup` method would also need to be modified to look in the tuple for the object point and if `None` call the `find` method.

I haven't carefully thought through all the implications of this (presumably the serializer and parser would also have to unpack and pack these tuples), but hopefully that's the start of an idea.

**Comment by tcmitchell** [comment]
Caching works really well for this type of problem. The issue is timing out or clearing the cache appropriately. We may be able to manage that at the document level if we're careful about things. But if it gets out of sync it may be hard to recover and lead to unpredictable results. That's not good.

What if you could generate such a cache within your application and then pass it to the `lookup` method as an optional parameter. `lookup` could then try the cache and fall back to a find if the cache does not include the object? On the large iGEM document we used on #381 takes 0.03 seconds to generate a full cache of the 10,280 objects. After that, lookups are essentially immediate. That would give the application control over the lifetime of the cache.

We could also keep the cache inside the document and give the application control over clearing it or giving it a time limit.

If we really want the document to manage it that's a larger project and would require a lot of test cases to find issues with various use cases. Even then I think we would still see some issues with it.

**Comment by tcmitchell** [comment]
Lookup acceleration was added to https://github.com/SynBioDex/SBOL-utilitites in SynBioDex/SBOL-utilitites#116 SynBioDex/SBOL-utilitites#118. See `build_reference_cache`, `cached_references` for building the cache for acceleration. See `find_child` and `find_top_level` for use of the reference cache.
