### ISSUE TITLE
Namespace can mismatch when full URI is supplied

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/pySBOL3#277]
During `TopLevel` creation, when a full URI is supplied but the namespace is not, pySBOL3 doesn't check if the default namespace matches the URI.

Example:
```
>>> sbol3.set_namespace('https://bbn.com/scratch/')
>>> doc = sbol3.Document()
>>> doc.add(sbol3.Activity('http://foo.org/bar'))
>>> print(doc.write_string(sbol3.NTRIPLES))
<http://foo.org/bar> <http://sbols.org/v3#displayId> "bar" .
<http://foo.org/bar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://sbols.org/v3#TopLevel> .
<http://foo.org/bar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/prov#Activity> .
<http://foo.org/bar> <http://sbols.org/v3#hasNamespace> <https://bbn.com/scratch/> .
```

Notice the final triple, with an illegal value for hasNamespace.
Validation also does not yet catch this error.

**Comment by tcmitchell** [comment]
What is the desired behavior when given a full URL as an identity and the prefix does not match the default namespace?
* Raise an exception because of the mismatch?
* Require a `namespace` argument in this case and raise an exception if the namespace argument is missing? (this is a variation of always raising an exception)
* Accept the full URL and assume everything other than the `displayId` portion of the URL is the object's namespace?
* Accept the full URL and assume that the shortest possible prefix is the `namespace`, and everything between the `namespace` and the `displayId` is the `local` portion?

I have added #278 for the validation issue which I consider orthogonal to the primary issue here.

**Comment by jakebeal** [comment]
Either of the ways to raise an exception would seem reasonable to me.
We should definitely not do the latter two.
