### ISSUE TITLE
Support rdflib 6.0

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL3#279]
The 6.0 release of rdflib has some breaking changes in the `graph.serialize` method.  Notably the method now returns a regular string rather than a bytestring.  This breaks pysbol's `Document.write_string` method.

See this build log for an example of this failure mode:
https://github.com/SynBioDex/sbol_factory/runs/3135729743?check_suite_focus=true#step:5:124

**Comment by tcmitchell** [comment]
Version 1.0b5 contains a workaround for this issue. It pins the RDFlib dependency at version 5.

**Comment by tcmitchell** [comment]
See https://github.com/RDFLib/rdflib/issues/1376 for a minor issue with rdflib 6.0.

**Comment by tcmitchell** [comment]
And see https://github.com/RDFLib/rdflib/issues/1376#issuecomment-885741449 for a workaround

**Comment by tcmitchell** [comment]
See https://github.com/RDFLib/OWL-RL/issues/44 for an issue about warnings emitted by owlrl which is a dependency of pyshacl. These will bother users in interactive tutorials that use pySBOL3 because pySBOL3 depends on pyshacl and these warnings show up in an interactive python interpreter after `import sbol3`.
