### ISSUE TITLE
Unable to Execute " i13504.encoding = SBOL_IUPAC_DNA "

### ISSUE THREAD

**Issue by PRUBHTEJ** [SynBioDex/pySBOL3#298]
I've been executing the code from COMBINE 2020 SBOL tutorials and while executing this statement in the Jupiter notebook, it returns the following error: - 

*NameError: name 'SBOL_IUPAC_DNA' is not defined*

<img width="1190" alt="Screenshot 2021-08-30 at 19 14 34" src="https://user-images.githubusercontent.com/47414674/131348991-83529318-1771-43b4-bad3-4319b8124478.png">

**Comment by tcmitchell** [comment]
Sorry for the trouble. The sequence encoding constants were updated as part of the SBOL 3.0.1 specification update. Please try `IUPAC_DNA_ENCODING` instead of `SBOL_IUPAC_DNA` and let us know how it goes. If that works ok for you we can have the COMBINE 2020 SBOL tutorial updated accordingly. 

Thanks for letting us know!

**Comment by PRUBHTEJ** [comment]
Thanks!
That works perfectly for me. 
<img width="1210" alt="Screenshot 2021-08-30 at 19 48 28" src="https://user-images.githubusercontent.com/47414674/131353755-c6a92a08-fda0-4ce8-81a5-89490b774db7.png">
