### ISSUE TITLE
Make SBOL objects sortable

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/pySBOL3#320]
In order to allow SBOL objects to be sortable I have found it useful to monkey-patch the following routine:

```
def identity_lt(self: sbol3.Identified, other: sbol3.Identified):
    return self.identity < other.identity
sbol3.Identified.__lt__ = identity_lt
```

Would it be generally a good idea to implement the ordering functions for `Identified`?

**Comment by tcmitchell** [comment]
Instead of monkey patching, can you use the `key` argument to [sorted](https://docs.python.org/3/library/functions.html#sorted) or [sort](https://docs.python.org/3/library/stdtypes.html#list.sort)?

```python
sorted(doc.objects, key=lambda x: x.identity)
```

I'm reluctant to make objects sortable by their `identity` because it seems an arbitrary field to choose, and it is very easy for applications to establish their own sort order using the standard Python sorting routines. I also think this makes the code that wants a sorted order more clear because it will explicitly state what the sort criteria is.

 _Can_ we make `Identified` objects sortable? Yes. _Should_ we? For me the answer is no.

**Comment by jakebeal** [comment]
I hadn't noticed that I would give sorted an argument so compactly; let me try using that

**Comment by jakebeal** [comment]
Yes, that will work.
