### ISSUE TITLE
Namespace validation breaks on read when default namespace differs

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/pySBOL3#337]
The current release introduced a critical breaking bug. If the default namespace is set, then pySBOL3 cannot read any object whose namespace does not match the default namespace.

Here is a minimal reproduction of the bug:
```
import sbol3

doc = sbol3.Document()
sbol3.set_namespace('http://foo.org')
doc.add(sbol3.Sequence('bar'))
assert not len(doc.validate())
doc.write('scratch.nt',sbol3.SORTED_NTRIPLES)

doc2 = sbol3.Document()
doc2.read('scratch.nt',sbol3.SORTED_NTRIPLES) # Successful read

sbol3.set_namespace('http://baz.com/')
doc3 = sbol3.Document()
doc3.read('scratch.nt',sbol3.SORTED_NTRIPLES)
# ValueError: Namespace must be a prefix of identity. Namespace http://baz.com/ is not a prefix of http://foo.org/bar.
```

**Comment by tcmitchell** [comment]
On #277 I [listed a number of options](https://github.com/SynBioDex/pySBOL3/issues/277#issuecomment-882608453) and seemingly missed one that I'd like to raise as a possibility.

* If a full URI is specified for identity AND a default namespace is set AND the identity does not match the default namespace, deduce the namespace from the identity and do so greedily

Greedily means we would use everything up until the last element of the path as the namespace. For example, `http://example.com/foo` would have `http://example.com` as the namespace, and `http://example.com/foo/bar/baz` would have `http://example.com/foo/bar` as the namespace.

This change would make it ok to mismatch between the default namespace and the identity passed to the constructor, instead of raising an exception. If a user is taking the time to put in a full URI, they would be saying, "ignore the default namespace, I want this URI." And if they want to pass a namespace as an argument we would check that there is a match between the two.

I think this is a legitimate fix to the bug in #277 where we ended up with a mismatch between the identity and the namespace because we blindly used the default namespace without trying to be smarter about things.

What are your thoughts, @jakebeal? If this sounds ok for the case above, I could write up pseudocode for the full logic including whether the identity is fully specified or not, whether a default namespace is set or not, and whether a namespace argument is provided or not.

Also tagging @bbartley to monitor the discussion and chime in with is experience from pySBOL and pySBOL2.
