### ISSUE TITLE
Adding Namespace to Document does not add to the document's namespace dictionary

### ISSUE THREAD

**Issue by tramyn** [SynBioDex/pySBOL3#37]
I want to add a Namespace object to an SBOL Document but this namespace variable in the Document class https://github.com/SynBioDex/pySBOL3/blob/3d1ad4a18b44dda3575d2b86ffd01d6455a94040/sbol3/document.py#L29)

doesn't get updated to reflect that this object was added to the document. Instead, I can see that the namespace was added to a list of object. Is this valid? What is the difference in usage between an SBOL Document's list of object vs. the namespace dictionary?

Here is an example code set up to test this behavior:
```
ns_uri = 'http://foo.com'
document = Document()
namespace1 = Namespace(name=sbol_constants.SBOL3_NS, type_uri=ns_uri)
document.add(namespace1)

actual_namespace1 = document.find(ns_uri)
self.assertEqual(namespace1, actual_namespace1)

added_namespaces = document.namespaces
self.assertDictEqual({sbol_constants.SBOL3_NS: ns_uri}, added_namespaces)
```

**Comment by tcmitchell** [comment]
The SBOL 3 Namespace entity is distinct from `Document.namespaces`. `Document.namespaces` are for recording the RDF namespaces found in an RDF document. Since this is an internal matter, `Document.namespaces` should be renamed to `Document._namespaces`.

SBOL 3 Namespaces should only get recorded in the Document's object list.
