### ISSUE TITLE
Eliminate empty lines in .nt serializations

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/pySBOL3#404]
RDFlib's .nt serialization is ending up with an empty line at the beginning of the file that doesn't need to be there. It's not harmful, but is unnecessary and ugly; can we eliminate this?

**Comment by tcmitchell** [comment]
RDFlib's N-Triples serialization has an extra blank line at the end. pySBOL3's sorted N-Triples format takes the output of RDFlib's N-Triples serialization and sorts it. The sort puts that empty blank line at the beginning.

I don't know why RDFlib puts an extra blank line at the end of an N-Triples file. Here is a short example of that:
```python
>>> import rdflib
>>> g = rdflib.Graph()
>>> g.add((rdflib.URIRef('sbol3'), rdflib.RDF.type, rdflib.URIRef('package')))
<Graph identifier=Nce436cfb72f04910be1cb0c2b4d1d3eb (<class 'rdflib.graph.Graph'>)>
>>> print(g.serialize(format='nt11'))
<sbol3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <package> .


>>> 
```

We can tackle this in a couple of different ways. We could remove the blank line in both N-Triples and Sorted N-Triples formats by filtering them. We could also filter out the blank line only in sorted N-Triples since it moves to the front of the file and is more obvious than the blank line at the end.

I don't know if this is a bug in the RDFlib N-Triples serialization, or if it is a feature.
