### ISSUE TITLE
Handle creating Component with invalid type_uri

### ISSUE THREAD

**Issue by tramyn** [SynBioDex/pySBOL3#63]
I am using the Component class to encode strains. The constructor for the class allows me to modify `type_uri` to change the default value from http://sbols.org/v3#Component to http://sbols.org/v3#Module . However, if I want to pass in a invalid URI to `type_uri`, the library will accept it and update the field accordingly. I don't think this should be allowed  and request that the library should add extra check to ensure that the value provided for type_uri should correctly follow a URI format.

Here is sample code used for testing this feature:
```
    def test_create_component_with_invalid_uri(self):
        document = Document()
        strain_XOR_11 = 'UWBF_XOR_11'
        input_strain = Component(name=strain_XOR_11,
                                 component_type=sbol_constants.SBO_FUNCTIONAL_ENTITY,
                                 type_uri='MODULE')
        document.add(input_strain)
        output_strain = document.find(strain_XOR_11)
        self.assertEqual(input_strain, output_strain)
        self.assertEqual(sbol_constants.SBOL_COMPONENT, output_strain.type_uri)

    def test_create_component_with_valid_uri(self):
        document = Document()
        strain_XOR_11 = 'UWBF_XOR_11'
        input_strain = Component(name=strain_XOR_11,
                                 component_type=sbol_constants.SBO_FUNCTIONAL_ENTITY,
                                 type_uri='http://sbols.org/v3#Module')
        document.add(input_strain)
        output_strain = document.find(strain_XOR_11)
        self.assertEqual(input_strain, output_strain)
        self.assertEqual('http://sbols.org/v3#Module', output_strain.type_uri)
```

**Comment by tcmitchell** [comment]
You shouldn't need to override the type_uri unless you are creating custom annotations or extensions. You are _allowed_ to override the type_uri so that you _can_ create custom annotations and extensions.

Both `'MODULE'` and `'http://sbols.org/v3#Module'` are valid URIs. The definition of a URI is really general and only a few characters are illegal.

```
>>> import rdflib
>>> uri1 = rdflib.URIRef('MODULE')
>>> 
>>> rdflib.URIRef('foo"bar')
foo"bar does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:foo"bar does not look like a valid URI, trying to serialize this will break.
rdflib.term.URIRef('foo"bar')
```

Note that per my comment on https://github.com/SynBioDex/pySBOL3/issues/62, `'http://sbols.org/v3#Module'` would not be allowed because it uses the SBOL namespace `http://sbols.org/v3#` for an entity that is not defined in the specification, namely `Module`. The library doesn't detect that, and probably won't. It's something you shouldn't do though. Other libraries might complain.

**Comment by jakebeal** [comment]
@tramyn I think you shouldn't be needing to make a Module in the first place, because that should just be a Component in SBOL3, where there is no longer a Component vs. Module distinction (see Section 10 of the spec on SBOL 2->3 mapping)

**Comment by tcmitchell** [comment]
@tramyn can this issue be closed or are there things that still need to be fixed?

**Comment by tramyn** [comment]
@tcmitchell Yes, I'm fine with closing.
