### ISSUE TITLE
Extension classes

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL3#7]
A neat and useful pattern that can be used to automatically register an extension class in the RDFtype : builder dictionary is based on metaclass as follows:
```
class SBOLMetaClass(type):
    def __new__(cls, clsname, superclasses, attributedict, type_uri=None):
        if type_uri is None:
             raise Exception('All SBOL class definitions must include an RDF type_uri as a keyword argument)
        register_in_data_model(type_uri, cls)
        return type.__new__(cls, clsname, superclasses, attributedict)

class SBOLObject(metaclass=SBOLMetaClass, type_uri='http://sbols.org#SBOLObject'):
    ...
```
Then if someone wants to define an extension class, they can use a simple pattern as follows:
```
class ExtensionClass(SBOLObject, type_uri='http://bbn.com#ExtensionClass'):
```
This class definition is then sufficient to automatically register the class' builder function.  Of course, anytime the user wants to define an extension class derived from an SBOL core class they MUST remember to specify the `type_uri`.  If the user forgets this, then it can be caught as an Exception.  (By way of contrast, in pySBOL2 it is much easier for a user to forget to register a class in the data model, which can result in lossy round tripping)

**Comment by tcmitchell** [comment]
We've gone a different way with extension classes. pySBOL3 has `CustomIdentified` and `CustomTopLevel` classes which an application can extend (if they choose) to define custom classes per Section 6.11 of the SBOL 3.0 spec.

In order to complete this issue we need some test cases that demonstrate creating and round-tripping custom classes, and we need at least a little bit of documentation on creating these custom extension classes. Those exercises will ensure that the implementation is sufficient.

**Comment by jakebeal** [comment]
I believe the likely path forward for this is going to be tied to the autogeneration library that has been created in OPIL. After that gets factored out (https://github.com/SD2E/opil/issues/150), then extension classes should be able to readily be created by reading in a new Ontology file.
