### ISSUE TITLE
`set_homespace` requires a terminating delimiter in the URL but the exception doesn't tell you that

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL3#80]
It took me a while to figure out that the issue causing the following exception was that the URL was missing a terminating `/`:
```
Traceback (most recent call last):
  File "time_series.py", line 4, in <module>
    sbol3.set_homespace('http://strateos.com')
  File "/Users/bbartley/Dev/git/sd2/opil/pySBOL3/sbol3/config.py", line 19, in set_homespace
    raise ValueError(f'Expected URL found {homespace}')
ValueError: Expected URL found http://strateos.com
```

**Comment by tcmitchell** [comment]
The check at https://github.com/SynBioDex/pySBOL3/blob/master/sbol3/config.py#L15 might be too restrictive in requiring a path. We could remove the path from that check. Section 5.1 of the spec indicates that `https://synbiohub.org` is a valid namespace. If that's the case, `http://strateos.com` should be valid as well.

In the first bullet in Section 5.1 (page 12):

> For example, a Component might have the URL https://synbiohub.org/public/igem/BBa_J23070, where namespace is https://synbiohub.org, local is public/igem, and displayId is BBa_J23070.

**Comment by tcmitchell** [comment]
Further clarification - `set_homespace` _does not_ require a trailing delimiter. A current unit test demonstrates that `https://github.com/synbiodex/pysbol3` is an acceptable "homespace" (default namespace), and it does not have a trailing delimiter. What is missing from `http://strateos.com` is a path, which is why it was rejected. As stated above, `set_homespace` needs to allow `http://strateos.com` or `https://synbiohub.org` so the path requirement needs to be dropped.
