### ISSUE TITLE
IntProperty does not support upper bound > 1

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL3#89]
This issue is blocking development of OPIL.
```
  File "/usr/local/lib/python3.7/site-packages/sbol3/int_property.py", line 41, in IntProperty
    raise ValueError('Upper bound > 1 not handled yet')
ValueError: Upper bound > 1 not handled yet
```

**Comment by tcmitchell** [comment]
The SBOL 3.0 data model doesn't require integer properties with upper bound greater than 1, so `IntListProperty` is not yet implemented. The same holds for Boolean, DateTime, and Float properties. None of these should be hard to implement, as they are largely copy/paste. We'll want to define Custom classes for the unit tests because no core class is available to use in these cases.
